#########################################################################
# VERSION 0.1.9
# AUTHOR:         Leonardo Santos <leonardofaria00@gmail.com>
# DESCRIPTION:    Image CentOS with PHP 7.3 and httpd 2.4
# TO_BUILD:       docker-compose build
# TO_RUN:         docker-compose up -d
#
# Dockerfile de construção de imagem utilizada pelo MD
#
# Container preparado e configurado para uso em desenvolvimento e teste
#########################################################################

version: "3.7"

services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
